language: generic

services:
  - docker

cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
    - ROS_REPO=main
  matrix:
    - ROS_DISTRO="kinetic"
    - ROS_DISTRO="kinetic" ROS_REPO=testing
    - ROS_DISTRO="melodic"
    - ROS_DISTRO="melodic" ROS_REPO=testing

install:
  - git clone -b master --quiet --depth=1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci

script:
  - .industrial_ci/travis.sh
