sudo: required
cache:
  - apt

language: generic
matrix:
  include:
    - name: "Xenial kinetic sdk 3.0.275"
      dist: xenial
      env: ROS_DISTRO=kinetic SDK_VERSION=3.0.275
    - name: "Xenial kinetic sdk 2.3.1536"
      dist: xenial
      env: ROS_DISTRO=kinetic SDK_VERSION=2.3.1536
    - name: "Xenial kinetic sdk 2.2.175"
      dist: xenial
      env: ROS_DISTRO=kinetic SDK_VERSION=2.2.175
    - name: "Bionic melodic sdk 3.0.275"
      dist: bionic
      env: ROS_DISTRO=melodic SDK_VERSION=3.0.275
    - name: "Bionic melodic sdk 2.3.1536"
      dist: bionic
      env: ROS_DISTRO=melodic SDK_VERSION=2.3.1536
    - name: "Bionic melodic sdk 2.2.175"
      dist: bionic
      env: ROS_DISTRO=melodic SDK_VERSION=2.2.175

env:
  global:
    - ROS_CI_DESKTOP="`lsb_release -cs`"
    - CI_SOURCE_PATH=$(pwd)
    - ROSINSTALL_FILE=$CI_SOURCE_PATH/dependencies.rosinstall
    - CATKIN_OPTIONS=$CI_SOURCE_PATH/catkin.options
    - ROS_PARALLEL_JOBS='-j8 -l6'
    - PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages

before_install:
  - sudo sh -c "echo \"deb http://packages.ros.org/ros/ubuntu $ROS_CI_DESKTOP main\" > /etc/apt/sources.list.d/ros-latest.list"
  - sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
  - sudo apt-get update -qq
  - sudo apt-get install dpkg
  - sudo apt-get install -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-ros-base
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - sudo rosdep init
  - rosdep update --include-eol-distros  # Support EOL distros.
  - sudo apt-get install python-catkin-tools

  if: dist=xenial
  - sudo apt install libvtk6.2 -y

  # Install EnsensoSDK
  - sudo apt update
  - sudo apt -y install wget
  - wget -O /tmp/ensenso.deb https://download.ensenso.com/s/ensensosdk/download?files=ensenso-sdk-$SDK_VERSION-x64.deb
  - sudo dpkg -i /tmp/ensenso.deb
  - sudo apt install -f -y
  - export ENSENSO_INSTALL=/opt/ensenso

install:
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws/src
  - catkin_init_workspace
  - cd ~/catkin_ws
  - catkin_make
  - source devel/setup.bash

  - cd ~/catkin_ws/src
  - ln -s $CI_SOURCE_PATH .
before_script:
  - cd ~/catkin_ws/src
  - wstool init
  - if [[ -f $ROSINSTALL_FILE ]] ; then wstool merge $ROSINSTALL_FILE ; fi
  - wstool up
  - cd ~/catkin_ws
  - rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO

script:
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - cd ~/catkin_ws
  - catkin_make -DCMAKE_BUILD_TYPE=Release
  - source devel/setup.bash
  # Force to run tests in sequence, because the file cams can interrupt each other
  - catkin_make run_tests -j1 && catkin_test_results