#!/usr/bin/env python
import rospy
import sys

import actionlib
from actionlib_msgs.msg import GoalStatus
from ensenso_camera_msgs.msg import RequestDataAction, RequestDataGoal
from ensenso_camera_msgs.msg import RequestDataMonoAction, RequestDataMonoGoal
from ensenso_camera_msgs.msg import TexturedPointCloudAction, TexturedPointCloudGoal


def main():
    loop_rate = rospy.get_param("~rate", 2)
    mono_serial = rospy.get_param("~mono_serial")
    stereo_namespace = rospy.get_param("~stereo_ns", "stereo")
    mono_namespace = rospy.get_param("~mono_ns", "mono")
    timeout = rospy.get_param("~timeout", 60)

    # Use different namespaces in order to prevent duplicate topic names.
    request_stereo_data_client_name = stereo_namespace + "/request_data"
    request_mono_data_client_name = mono_namespace + "/request_data"
    texture_point_cloud_client_name = stereo_namespace + "/texture_point_cloud"

    request_stereo_data_client = actionlib.SimpleActionClient(request_stereo_data_client_name, RequestDataAction)
    request_mono_data_client = actionlib.SimpleActionClient(request_mono_data_client_name, RequestDataMonoAction)
    texture_point_cloud_client = actionlib.SimpleActionClient(texture_point_cloud_client_name, TexturedPointCloudAction)

    clients_names = [request_stereo_data_client_name, request_mono_data_client_name, texture_point_cloud_client_name]
    clients = [request_stereo_data_client, request_mono_data_client, texture_point_cloud_client]
    for client_name, client in zip(clients_names, clients):
        rospy.loginfo("Trying to connect to: {}".format(client_name))
        if not client.wait_for_server(rospy.Duration(timeout)):
            rospy.logerr("The camera node is not running!")
            sys.exit()
        rospy.loginfo("Connected")

    request_stereo_data_goal = RequestDataGoal()
    request_stereo_data_goal.request_point_cloud = True

    request_mono_data_goal = RequestDataMonoGoal()
    request_mono_data_goal.request_rectified_images = True

    rate = rospy.Rate(loop_rate)
    while not rospy.is_shutdown():
        request_stereo_data_client.send_goal(request_stereo_data_goal)
        request_mono_data_client.send_goal(request_mono_data_goal)

        request_stereo_data_client.wait_for_result()
        request_mono_data_client.wait_for_result()

        if request_stereo_data_client.get_state() != GoalStatus.SUCCEEDED:
            rospy.logwarn("Stereo action was not successful.")
        else:
            error = request_stereo_data_client.get_result().error
            if error.code != 0:
                rospy.logerr("Stereo error {}: {}".format(error.code, error.message))

        if request_mono_data_client.get_state() != GoalStatus.SUCCEEDED:
            rospy.logwarn("Mono action was not successful.")
        else:
            error = request_mono_data_client.get_result().error
            if error.code != 0:
                rospy.logerr("Mono error {}: {}".format(error.code, error.message))

        texture_goal = TexturedPointCloudGoal()
        texture_goal.use_opengl = True
        texture_goal.publish_results = True
        texture_goal.mono_serial = mono_serial
        texture_goal.far_plane = 4000.0
        texture_goal.near_plane = 100.0

        texture_point_cloud_client.send_goal(texture_goal)
        texture_point_cloud_client.wait_for_result()

        rate.sleep()


if __name__ == "__main__":
    try:
        rospy.init_node("color_point_cloud")
        main()
    except rospy.ROSInterruptException:
        pass
