#!/usr/bin/env python3
import sys

import ensenso_camera.ros2 as ros2py

RequestData = ros2py.import_action("ensenso_camera_msgs", "RequestData")
RequestDataMono = ros2py.import_action("ensenso_camera_msgs", "RequestDataMono")
TexturedPointCloud = ros2py.import_action("ensenso_camera_msgs", "TexturedPointCloud")


def _main(node_name):
    node = ros2py.create_node(node_name, args=sys.argv)

    loop_rate = ros2py.get_param(node, "rate", 2.0)
    mono_serial = ros2py.get_param(node, "mono_serial")
    stereo_namespace = ros2py.get_param(node, "stereo_ns", "stereo")
    mono_namespace = ros2py.get_param(node, "mono_ns", "mono")
    timeout = ros2py.get_param(node, "timeout", 60)

    # Use different namespaces in order to prevent duplicate topic names.
    request_stereo_data_client_name = stereo_namespace + "/request_data"
    request_mono_data_client_name = mono_namespace + "/request_data"
    texture_point_cloud_client_name = stereo_namespace + "/texture_point_cloud"

    request_stereo_data_client = ros2py.create_action_client(node, request_stereo_data_client_name, RequestData)
    request_mono_data_client = ros2py.create_action_client(node, request_mono_data_client_name, RequestDataMono)
    texture_point_cloud_client = ros2py.create_action_client(node, texture_point_cloud_client_name, TexturedPointCloud)

    clients = [request_stereo_data_client, request_mono_data_client, texture_point_cloud_client]
    ros2py.wait_for_servers(node, clients, timeout_sec=timeout)

    request_stereo_data_goal = RequestData.Goal()
    request_stereo_data_goal.request_point_cloud = True

    request_mono_data_goal = RequestDataMono.Goal()
    request_mono_data_goal.request_rectified_images = True

    request_clients = [request_stereo_data_client, request_mono_data_client]
    request_goals = [request_stereo_data_goal, request_mono_data_goal]

    def main_loop():
        stereo_response, mono_response = ros2py.send_action_goals(node, request_clients, request_goals)

        if not stereo_response.successful():
            node.get_logger().warn("Acquiring stereo data was not successful.")

        if not mono_response.successful():
            node.get_logger().warn("Acquiring mono data was not successful.")

        stereo_result = stereo_response.get_result()
        if stereo_result.error.code != 0:
            node.get_logger().error(ros2py.format_error(stereo_result.error, "Error while acquiring stereo data!"))
            return

        mono_result = mono_response.get_result()
        if mono_result.error.code != 0:
            node.get_logger().error(ros2py.format_error(mono_result.error, "Error while acquiring mono data!"))
            return

        texture_goal = TexturedPointCloud.Goal()
        texture_goal.use_opengl = True
        texture_goal.publish_results = True
        texture_goal.mono_serial = mono_serial
        texture_goal.far_plane = 4000.0
        texture_goal.near_plane = 100.0

        node.get_logger().info("Texturing point cloud.")
        ros2py.send_action_goal(node, texture_point_cloud_client, texture_goal)

    ros2py.execute_at_rate(node, main_loop, loop_rate)


def main():
    ros2py.wrap_main_function(_main, "color_point_cloud")


if __name__ == "__main__":
    main()
